### ISSUE TITLE
Not able to read out Subcomments

### ISSUE THREAD

**Issue by Infinest** [SirCmpwn/RedditSharp#139]
This is what i've been doing

 var subreddit = reddit.GetSubreddit("/r/targetreddit");

            foreach (var post in subreddit.New.Take(60))
            {
                //Console.WriteLine("THREAD : {0}", post.Title);
                    //Console.WriteLine(post.CommentCount.ToString()); (This normally shows the real number with subcomments)
                    foreach (var comment in post.Comments)
                    {
                     //Here only the parent comments exist. Am i just stupid or why is that?

**Comment by SirCmpwn** [comment]
Try calling comment.Init or comment.InitAsync.

**Comment by Infinest** [comment]
I think i'm doing something wrong. Could you give me an example with this code:
My reddit class is simply called 'reddit'

  foreach (var post in subreddit.New.Take(120))
            {
                post.Init(reddit, reddit.GetToken(post.Url), new WebAgent());
                Console.WriteLine("THREAD : {0}", post.Title);
                    Console.WriteLine(post.CommentCount.ToString());
                    foreach (var comment in post.ListComments())
                    {
                      try{
                      //do stuff
                      }
                      catch (Exception ex)
                      {
                          Console.WriteLine("exception: {0}", ex.Message);
                      }
                    }
            }

**Comment by SirCmpwn** [comment]
Init the *comment*, not the post.

**Comment by Infinest** [comment]
I left that in there at accident. I already did try it with comments
I think i'm just really dumb right now.

comment.Init(reddit, reddit.GetToken(post.Url), new WebAgent(), null);

**Comment by SirCmpwn** [comment]
I don't know, then. Good luck. This project is maintained by its users, so it's up to you to get debugging.

**Comment by Infinest** [comment]
Is that actually just a fault on my end or something wrong with redditsharp itself?

I've seen that another person before me also had problem with this.

**Comment by SirCmpwn** [comment]
I don't know. A [significant amount](https://github.com/SirCmpwn/RedditSharp/blame/master/RedditSharp/Things/Comment.cs) of RedditSharp was not written by me.

**Comment by Syke94** [comment]
@Infinest 

You need to use a recursive method.

This line here: `foreach (var comment in post.Comments)` will only return the top-level comments on a post, each `Comment` object has a readonly `Comments` property on [line 116](https://github.com/SirCmpwn/RedditSharp/blob/master/RedditSharp/Things/Comment.cs#L116) which returns `IList<Comment>`, containing all child comments, and each of those child comments may or may not have their own children.

This method will flatten the comment tree into a list that includes all comments in the post, not just the top-level ones. In theory, anyway. I can't test it right now but hopefully you at least get the idea.

``` csharp
public static List<Comment> GetAllComments( this Post post )
{
    var comments = new List<Comment>();

    Action<IList<Comment>> GetCommentsRecursive;
	GetCommentsRecursive = delegate( IList<Comment> children )
    {
		if( children == null || children.Count == 0 )
			return;
		
		comments.AddRange( children );
		
		foreach( var child in children )
			GetCommentsRecursive( child.Comments );
    };
	
	GetCommentsRecursive( post.Comments );
	return comments;
}
```

**Comment by Infinest** [comment]
I actually tried that before but maybe i probably just messed up. Anyways thank you so much for helping me I appreciate it
