### ISSUE TITLE
Ability to set User Agent

### ISSUE THREAD

**Issue by guyintruck** [SirCmpwn/RedditSharp#141]
Would be very helpful and would allow us to comply with Reddit's API TOS.

**Comment by SirCmpwn** [comment]
You can set a user agent. `RedditSharp.WebAgent.UserAgent = "...";`

Also, it has a sensible default so you aren't violating the terms even if you don't override it.

**Comment by guyintruck** [comment]
It would be advantageous to have this exposed in RedditSharp.Reddit.  I'm not seeing how one can set the user agent from that class.  Otherwise one is left with using WebAgent and building from their, which is less than ideal.

**Comment by YMIndustries** [comment]
RedditSharp exposes its internal WebAgent, so you can just reach in and change that property.

**Comment by SirCmpwn** [comment]
It's a static property on the WebAgent class. Not difficult to modify.

**Comment by guyintruck** [comment]
Thank you SirCmpwn, You are correct.
