### ISSUE TITLE
Sorting/JSON

### ISSUE THREAD

**Issue by ghost** [SirCmpwn/RedditSharp#152]
https://www.reddit.com/r/csharp/comments/2pl7k1/redditsharp_documentation/cqdfqlj

Sort enum needs to be cast to lower case otherwise sorting is ignored by reddit's json API.

Also, any thoughts on extending this to sorting of post comments? pretty easy implementation:

  public List<Comment> ListComments(int? limit = null, Sort sorting = Sort.New)
        {
            var url = string.Format(GetCommentsUrl, Id);
            
            url += string.Format("?sort={0}", Enum.GetName(typeof(Sort), sorting).ToLower());

etc etc

}

**Comment by SirCmpwn** [comment]
Sure, go for it.
