### ISSUE TITLE
FileNotFoundException was unhandled by user code.

### ISSUE THREAD

**Issue by sambunting** [SirCmpwn/RedditSharp#159]
I seem to be getting an error/warning when running a piece of "Test code" for RedditSharp. The dialog which appears says `FileNotFoundException was unhandled by user code.` With some additional details of:

`An exception of type 'System.IO.FileNotFoundException' occurred in RedditSharp.DLL but was not handled in user code

Additional information: Could not load file or assembly 'System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.`

Personally, I think that the error is being caused by another warning which is `Reference to type 'System.Net.Security.RemoteCertificateValidationCallback' claims it is defined in 'c:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\WindowsPhone\v8.1\System.dll', but it could not be found`

My code if it helps is:

    var reddit = new Reddit();
    var subreddit = reddit.GetSubreddit("/r/programming");

    foreach (var post in subreddit.Hot.Take(1))
    {
         Test.Text = post.Title;
    }

I've tried fixing the problem, but couldn't find anywhere. Any Help would be appreciated.

**Comment by SirTony** [comment]
Looks to me that you're trying to run the application using the version of the .NET framework that ships with the Windows Phone 8.1 SDK. Try installing the full [.NET Framework](https://www.microsoft.com/en-us/download/details.aspx?id=30653) and see if the error goes away.

**Comment by sambunting** [comment]
Thanks, sounds like I have got a bit of information.

Ran into another issue though, It says `Failed to add reference to 'RedditSharp'.` While installing the NuGet Package. I imagine its more of an issue of the NuGet manager, but I can seem to install any other package fine.

**Comment by SirCmpwn** [comment]
Any more errors than that? Are you trying to use RedditSharp with WP8?

**Comment by sambunting** [comment]
I was using WP8 where I got the `FileNotFoundException was unhandled by user code.` error. But for the `Failed to add reference to 'RedditSharp'.` error in the NuGet manager, I was using Windows App in C#.

**Comment by SirCmpwn** [comment]
Windows Apps can't use full blown .NET either. RedditSharp is unsupported for Windows Apps.
