### ISSUE TITLE
Objects.

### ISSUE THREAD

**Issue by Sven65** [SirCmpwn/RedditSharp#160]
The fact that the 
```cs
var reddit = new Reddit();
```
is a var makes me unable to use it outside of the function it was declared in.
Can't it just be like a object that can be used everywhere?
If not, why?

Thanks

\- Sven

**Comment by Aniel** [comment]
You can just write:
```csharp
Reddit myReddit = new Reddit();

-Aniel

**Comment by SirCmpwn** [comment]
This is due to your failure to understand basic C# concepts, not due to any problem within RedditSharp.

**Comment by corylulu** [comment]
'var' in C# is a compiler-only term. 'var' is just a shorthand way to declare a variable when the compiler _knows_ what type it's being set to. Since you are setting it equal to a 'Reddit' object type, it will be that type at runtime. So,

     var reddit = new Reddit(); 

is literally the same thing as writing:

     Reddit reddit = new Reddit();

**Comment by SirTony** [comment]
> 'var' is just a shorthand way to declare a variable when the compiler knows what type it's being set to.

The compiler always knows what type something is. `var` is just the type inference keyword (same as C++'s `auto`), so it's more accurate to say that `var` instructs the compiler to figure out the variable type itself, rather than being told what type it is by the programmer.

**Comment by SirCmpwn** [comment]
We don't all need to give the scrub our personal version of the explanation.
