### ISSUE TITLE
Merging multiple subreddits

### ISSUE THREAD

**Issue by isaac2004** [SirCmpwn/RedditSharp#162]
Hey there,

Do you intend at any point to extending this library to handle concatenating subreddits, ir

http://reddit.com/earthporn+cityporn+windowporn/.json?limit=100

Right now it seems you go straight to the about page for a single subreddit, which is fine. Worst case you can pass in a list of subreddits and get an array from them which isn't anything.

**Comment by SirCmpwn** [comment]
See "Development" [here](https://github.com/SirCmpwn/RedditSharp#development).

**Comment by isaac2004** [comment]
I can add it, just wanted to make sure you weren't going to do something.
