### ISSUE TITLE
2,5sec to load 25 posts?

### ISSUE THREAD

**Issue by theWalli** [SirCmpwn/RedditSharp#178]
Is it normal for the API to take ~2,5 sec to load the 25 first posts of a subreddit?
The code I use is this (`_reddit` is already logged in):

    var sub = await _reddit.GetSubredditAsync(subreddit);
    var subPosts = sub.New.Take(25).ToList();

**Comment by SirCmpwn** [comment]
Yes. Reddit API is slow. It's faster if you use OAuth.
