### ISSUE TITLE
Is the TestRedditSharp project working?

### ISSUE THREAD

**Issue by AMWJ** [SirCmpwn/RedditSharp#179]
I'm trying to run the included test project on Windows 8.1 using Visual Studio 2015, not using OAuth, and I receive a `System.ArgumentOutOfRangeException` on the last line of `GetThingByFullname`, when trying to get comment `t1_ciif2g7`.

The code seems to expect `data.children` to contain something, which it will then parse into a Comment object. But the returned JSON has just an empty list there, causing an error when the code tries to get index 0.

Am I running this incorrectly? I can verify that attempting to access `https://www.reddit.com/api/info.json?id=t1_ciif2g7` with my web browser also returns the same JSON that the code is receiving, with an empty `data.children`.

**Comment by SirCmpwn** [comment]
It's not meant to be some thing you use to demonstrate that RedditSharp works. It's just some code that I change whenever I need to test something because of the issues this project has with unit tests.

**Comment by AMWJ** [comment]
Thank you.
