### ISSUE TITLE
Updating the API for Windows 10 clients

### ISSUE THREAD

**Issue by rjb8682** [SirCmpwn/RedditSharp#180]
Is there any chance that you'd be updating this for Windows 10 UWP apps? A lot of the annotations and ways of communicating through the web and such are not used anymore

**Comment by SergueiFedorov** [comment]
Could you please elaborate on this?

**Comment by rjb8682** [comment]
of course! So I attempted to use the API with a Universal Windows App (for the Windows Store) but a lot of the functionality wasn't supported in those UWP api's. I was just curious if you there were plans to make this work in a UWP environment so this can be used in, and then published with, a Windows 10 Store App

**Comment by SergueiFedorov** [comment]
Let me grab the latest version and try to apply it in a UWP project and see which components have issues because of the unsupported APIs

**Comment by rjb8682** [comment]
alright perfect. Thanks a ton!

**Comment by SergueiFedorov** [comment]
I'll let you know if it's feasible, you're going to have to wait until the weekend though!

**Comment by rjb8682** [comment]
No problem at all. It would be amazing if it does work out but if not, it's no biggy at all. I appreciate the help

**Comment by SirCmpwn** [comment]
Not interested in this upstream. I think there are forks of RedditSharp you can use for that purpose.

**Comment by rjb8682** [comment]
If you don't mind, what fork are you referring to? Also wasn't @SergueiFedorov looking into it already? Thanks!

**Comment by SirCmpwn** [comment]
I don't keep track of the forks, I've just seen them in passing. And it'd be great if @SergueiFedorov looks into this, but he should publish his work in another repository.

**Comment by rjb8682** [comment]
Any specific reason why you wouldn't want to go down that route? Just curious, honestly. Seems like there's a big opportunity in UWP apps, so I guess i'm just surprised. No disrespect intended, by the way

**Comment by SirCmpwn** [comment]
Supporting them has some implications for the design and implementation of RedditSharp that I'm not interested in. I have no desire to support UWP apps and as a result I would rather not degrade the quality of this library's codebase to support it.

**Comment by SergueiFedorov** [comment]
@SirCmpwn I'll try to look for a fork that looking for something like this. It seems like a lot of them are pretty far behind. I might as well just use my own fork for that.

**Comment by rjb8682** [comment]
Gotcha. Much appreciated for the explanation
