### ISSUE TITLE
IWebAgent purpose and issue with WebAgent.RootDomain

### ISSUE THREAD

**Issue by CrustyJew** [SirCmpwn/RedditSharp#182]
I have a question, what exactly is the purpose of IWebAgent. The interface doesn't seem to add any benefit, and it's currently complicating my life instead of just passing WebAgent because the RootDomain doesn't exist in the interface.

This leads me to the actual issue I'm working on. Because RootDomain is static, I can't have multiple requests with OAuth and without unless I keep changing the static variable. Basically it shouldn't be static, but changing it to an instance variable makes it harder to access since it's not in the interface.

Does anyone actually make use of the IWebAgent interface?

**Comment by SirCmpwn** [comment]
It's used for things like connecting to Reddit with a proxy.

**Comment by SirCmpwn** [comment]
You can make your own IWebAgent implementation and change what RedditSharp uses to it.

**Comment by CrustyJew** [comment]
Ahhh that makes sense. So the best way around that sounds like it would be to implement my own version of IWebAgent that doesn't have a static member for the RootDomain.

But that requires re-compiling it with my own implementation baked in to replace WebAgent or am I missing something?

**Comment by SirCmpwn** [comment]
Your software can provide RedditSharp with your implementation of IWebAgent without recompiling RedditSharp.

**Comment by CrustyJew** [comment]
I see that you can pass it in on some of the things like Wiki, but not on the main "Reddit" class

**Comment by SirCmpwn** [comment]
Apparently you can't. See the bottom of the readme for details on how to fix this.

**Comment by CrustyJew** [comment]
Haha sounds good. I've also got some stuff mostly ready to go for a feature to read / parse Moderator Toolbox notes that I can include. Do you have any preference if it's in one pull request or 1 for adding the WebAgent stuff to "Reddit" and one pull for the Toolbox notes? It doesn't really matter to me, just don't know if you have a preference.

**Comment by SirCmpwn** [comment]
Separate PRs are usually better.

**Comment by CrustyJew** [comment]
Sounds good, hopefully I'll have those sent sooner than later, thanks for the help.
