### ISSUE TITLE
Comment.Remove doesn't work

### ISSUE THREAD

**Issue by mongrel73** [SirCmpwn/RedditSharp#198]
Trying to remove a comment (when signed in, able to post comment replies etc.) gives this error:

System.Net.WebException was unhandled
  HResult=-2146233079
  Message=The remote server returned an error: (403) Forbidden.
  Source=System
  StackTrace:
       at System.Net.HttpWebRequest.GetResponse()
       at RedditSharp.Things.Comment.RemoveImpl(Boolean spam)
       at RedditSharp.Things.Comment.Remove()
       at [my callstack]
  InnerException: 

Response property:

    IsFromCache: false
    IsMutuallyAuthenticated: false
    LastModified: {10/11/2015 15:26:32}
    Method: "POST"
    ProtocolVersion: {1.1}
    ResponseUri: {https://www.reddit.com/api/remove}
    Server: "cloudflare-nginx"
    StatusCode: Forbidden
    StatusDescription: "Forbidden"
    SupportsHeaders: true

{
  "m_HttpResponseHeaders": [
    "Transfer-Encoding",
    "Connection",
    "x-ua-compatible",
    "x-frame-options",
    "x-content-type-options",
    "x-xss-protection",
    "Vary",
    "Cache-Control",
    "Content-Type",
    "Date",
    "Expires",
    "Server",
    "X-Moose",
    "Strict-Transport-Security",
    "CF-RAY"
  ],
  "m_Uri": "https://www.reddit.com/api/remove",
  "m_Certificate": null,
  "m_Version": {
    "Major": 1,
    "Minor": 1,
    "Build": -1,
    "Revision": -1,
    "MajorRevision": -1,
    "MinorRevision": -1
  },
  "m_StatusCode": 403,
  "m_ContentLength": -1,
  "m_Verb": "POST",
  "m_StatusDescription": "Forbidden",
  "m_MediaType": null
}

**Comment by CrustyJew** [comment]
Is this your own comment you are trying to remove or are you trying to remove it as a mod action?

**Comment by mongrel73** [comment]
My own comment.

**Comment by CrustyJew** [comment]
You want to call Del() than instead of Remove(). Remove() is the mod action

**Comment by mongrel73** [comment]
Is Del() a method on the Comment class? It doesn't show up for me. This is the metadata for the Comment class as I see it:

    namespace RedditSharp.Things
    {
        public class Comment : VotableThing
        {
            public Comment();
    
            [JsonProperty("approved_by")]
            public string ApprovedBy { get; set; }
            [JsonProperty("author")]
            public string Author { get; set; }
            [JsonProperty("author_flair_css_class")]
            public string AuthorFlairCssClass { get; set; }
            [JsonProperty("author_flair_text")]
            public string AuthorFlairText { get; set; }
            [JsonProperty("banned_by")]
            public string BannedBy { get; set; }
            [JsonProperty("body")]
            public string Body { get; set; }
            [JsonProperty("body_html")]
            public string BodyHtml { get; set; }
            [JsonIgnore]
            public IList<Comment> Comments { get; }
            [JsonProperty("gilded")]
            public int Gilded { get; set; }
            [JsonProperty("link_id")]
            public string LinkId { get; set; }
            [JsonProperty("link_title")]
            public string LinkTitle { get; set; }
            [JsonProperty("num_reports")]
            public int? NumReports { get; set; }
            [JsonIgnore]
            public Thing Parent { get; }
            [JsonProperty("parent_id")]
            public string ParentId { get; set; }
            public override string Shortlink { get; }
            [JsonProperty("subreddit")]
            public string Subreddit { get; set; }
    
            public void EditText(string newText);
            public Comment Init(Reddit reddit, JToken json, IWebAgent webAgent, Thing sender);
            [AsyncStateMachine(typeof(<InitAsync>d__11))]
            [DebuggerStepThrough]
            public Task<Comment> InitAsync(Reddit reddit, JToken json, IWebAgent webAgent, Thing sender);
            public void Remove();
            public void RemoveSpam();
            public Comment Reply(string message);
            public void SetAsRead();
        }
    }

**Comment by mongrel73** [comment]
There is a Del() in Post.cs though... the implementation seems to be pretty much exactly the same as Comment.cs's RemoveImpl(). Does this method work for others?

**Comment by CrustyJew** [comment]
https://github.com/SirCmpwn/RedditSharp/blob/72e86d8d1b6742bf82b1da4da0d8530420c89d3b/RedditSharp/Things/Comment.cs#L210-L213

Do you have the latest version?

**Comment by mongrel73** [comment]
Hmm... yes, according to NuGet. 1.0.19. I can see in the Git repo that the Del method is in there (looks like the difference is the "spam" boolean - which makes sense as I guess I can't mark a comment as spam unless I'm a mod). 

Could it be the latest code hasn't been pushed to NuGet?

**Comment by CrustyJew** [comment]
Yeah my guess is the NuGet package needs updated. Looks like the commit adding Del() to comments was about a month ago which is about when the NuGet package was last updated, so it's possible it's not included.

**Comment by mongrel73** [comment]
Ok, fair enough. Is there a process for updating the package? Can I do it? Or, do you know of a workaround I could use?

**Comment by CrustyJew** [comment]
I'm not sure who manages the NuGet package, that'll have to be answered by @SirCmpwn

**Comment by SirCmpwn** [comment]
@RobThree is responsible for that.

**Comment by RobThree** [comment]
Run [`Update-Package RedditSharp`](https://www.nuget.org/packages/RedditSharp/1.0.20) and you're done :wink:

**Comment by mongrel73** [comment]
Fixed. Thanks.

**Comment by RobThree** [comment]
You're welcome ;)
