### ISSUE TITLE
Can't seem to limit the number of comments being returned.

### ISSUE THREAD

**Issue by tomnolan95** [SirCmpwn/RedditSharp#209]
I'm attempting to retrieve a number of comments for a specific user e.g 25, setting a limit to the number of comment I want to retrieve doesn't seem to do anything, it always seems to just pull back all comments regardless if I try limit it or not.

var comments = RedditUser.GetComments(Sort.New, 25, From.All)

That's what I'm using to try do it, apologies if I'm missing something blatant, any help is appreciated.

Tom.

**Comment by SirCmpwn** [comment]
Better to use user.GetComments(...).Take(25)

**Comment by tomnolan95** [comment]
Using .Take() still doesn't seem to be limiting the comment number though. It's still returning the full number of comments. Thanks for taking the time to reply.

**Comment by SirCmpwn** [comment]
Can you post more context?

**Comment by tomnolan95** [comment]
So what I'm trying to do is get say UserX's last 25 comments, after getting those comments I'm feeding them into a BarChart to show the number of comments on a certain day. When trying to get the 25 comments for UserX I can't seem to get just the 25 comments, if UserX had 50 comments in total I'd get 50 comments returned to me not 25 while using:

 var comments = redditUser.GetComments(Sort.New, 25, FromTime.All).Take(25);

**Comment by tomnolan95** [comment]
It's working now all of a sudden so all's good.
