### ISSUE TITLE
Can't edit my own comment

### ISSUE THREAD

**Issue by Krasiu** [SirCmpwn/RedditSharp#211]
Hey, I've changed the error handling a bit to check what is the exact error.

```
{
  "errors": [
    [
      "NOT_AUTHOR",
      "you can't do that",
      "thing_id"
    ]
  ]
}
```

I am definitely author of the comment I am trying to Edit.

**Comment by chuggafan** [comment]
I can't replicate this error and I'm running a bot that is editing it's own comment nearly 100-200 times a day, can someone close this now? or does this still happen

**Comment by CrustyJew** [comment]
It doesn't appear to happen that I know of. I'm closing this issue for now unless someone can replicate
