### ISSUE TITLE
How To Use Listing<> With Private Messages

### ISSUE THREAD

**Issue by Mrunited12** [SirCmpwn/RedditSharp#213]
I have tried everything, but I can not make a Listing<> with private messages. It says "No constructor takes 1 argument."

**Comment by SirCmpwn** [comment]
Since a PM can be a Comment or a PrivateMessage, you have to use Listing<Thing> and cast it yourself.

**Comment by Mrunited12** [comment]
How would I go about doing this?

**Comment by SirCmpwn** [comment]
RedditSharp reddit;
    for (var message in reddit.User.PrivateMessages)
    {
        var pm = message as PrivateMessage;
        var comment = message as Comment;
        if (pm != null) ...
        if (comment != null) ...
    }

**Comment by Mrunited12** [comment]
Thank you very much for your help!

Just wanted to also say thank you for making this wrapper :)

**Comment by Mrunited12** [comment]
Also, with the  var comment = message as Comment; I am getting the error: 

Cannot convert type 'RedditSharp.Things.PrivateMessage' to 'RedditSharp.Things.Comment' via a reference conversion, boxing conversion, unboxing conversion, wrapping conversion, or null type conversion

**Comment by SirCmpwn** [comment]
Use `if (message is Comment) { var comment = (Comment)message; ... }` and a similar thing for testing if it's a PM.

**Comment by Mrunited12** [comment]
Thanks a lot :)
