### ISSUE TITLE
Request forbidden by administrative rules.

### ISSUE THREAD

**Issue by isaac2004** [SirCmpwn/RedditSharp#218]
```
var reddit = new Reddit();
var user = reddit.LogIn("username", "password");
 var foo = user.UnreadMessages.Take(10);
```

This throws a WebException, and response is 

<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>

Do you know if this request is no longer permitted?

**Comment by SirTony** [comment]
Username/password login isn't allowed anymore as of March 17 as per the [new API terms](https://redd.it/3xdf11). If you want to make authenticated requests with the API you have to use OAuth2.

**Comment by TheRealBobTheLawyer** [comment]
SirTony, how do you do that with Redditsharp?  I can't figure it out.  The readme isn't helpful.  Seems like I should be using AuthProvider, but I can't figure out how that connects with the rest of the code.
