### ISSUE TITLE
Using OAuth2

### ISSUE THREAD

**Issue by TheRealBobTheLawyer** [SirCmpwn/RedditSharp#222]
Can someone give me some sample code that uses OAuth2 for authentication?  I've been looking at the code, and I can't really figure it out.  The readme isn't helpful about this.

I asked in a few comments elsewhere, but I think this is a better place for my question.

**Comment by CrustyJew** [comment]
```
var ap = new AuthProvider( _clientId, _clientSecret, _redirectUri, _webAgent );
                AccessToken = ap.GetOAuthToken( _uname, _pass );
                _webAgent.AccessToken = AccessToken;
```

Basically you need to create an instance of the AuthProvider class with a client id and secret from Reddit (setup under "preferences" -> "apps") and then call GetOAuthToken() using a username and password which will return an access token which is good for a certain amount of time. 

This is for bot development though and if you are wanting to use it as authentication to your application, you should check out https://github.com/tparnell8/OwinOAuthProviders which has support for refresh tokens etc.

**Comment by TheRealBobTheLawyer** [comment]
Thank you for your repsonse.  Yes, this is for bot development.  Isn't the webagent controlled in Reddit.cs?  

```
            IWebAgent _webAgent = new WebAgent();
            AuthProvider auth = new AuthProvider(_clientId, _clientSecret, "http://127.0.0.1:65010/authorize_callback", _webAgent);
            string AccessToken = auth.GetOAuthToken(_uname, _pass);
            _webAgent.AccessToken = AccessToken;
            reddit = new Reddit(_webAgent);

            subreddit = reddit.GetSubreddit("/r/bobthelawyer");
            wiki = subreddit.Wiki;
            wiki.EditPage("index", "A");

```

Running that throws up as soon as it tries to edit the wiki page.

If I don't use a custom webagent and pass the access token into my Reddit object, like so:
```
            AuthProvider auth = new AuthProvider(_clientId, _clientSecret, "http://127.0.0.1:65010/authorize_callback");
            string AccessToken = auth.GetOAuthToken(_uname, _pass);
            reddit = new Reddit(AccessToken);

            subreddit = reddit.GetSubreddit("/r/bobthelawyer");
            wiki = subreddit.Wiki;
            wiki.EditPage("index", "A"); Console.WriteLine("A");
            wiki.EditPage("index", "B"); Console.WriteLine("B");
            wiki.EditPage("index", "C"); Console.WriteLine("C");
```
The bot will consistently break before setting the wiki page to "C".  I assumed this is a problem with authentication.  The error I get is a Webexception in System.dll because the operation timed out.  This is the same error as when I authenticate using username and password.

Thanks for the help!

**Comment by CrustyJew** [comment]
The webagent _can_ be controlled in Reddit.cs but you can also pass a custom implementation which is what I was doing in the snippet I copied for you.

Actually there seems to be an issue with Reddit's API and it rate limiting editing wiki pages fairly severely. I've run into it as well after a couple (less than 3) quick edits it tends to time out for a while. If it is editing the wiki to A and B then auth is working though.

**Comment by TheRealBobTheLawyer** [comment]
> The webagent can be controlled in Reddit.cs but you can also pass a custom implementation which is what I was doing in the snippet I copied for you.

Ah.  So I should not be using Reddit.cs I guess.  

> Actually there seems to be an issue with Reddit's API and it rate limiting editing wiki pages fairly severely. 

It's not just the wiki.  
Like, I've put sleeps between each wiki edit (I've gone upto 20 seconds).  It still doesn't work.  Changing the third wiki edit to a reinitializing of my reddit variable with the authtoken also freezes at that point.  The issue always seems to be the third call.  This is the same thing that happened when I used username and password authentication.
