### ISSUE TITLE
Move RedditSharp to it's own repo/organization?

### ISSUE THREAD

**Issue by Kkloss** [SirCmpwn/RedditSharp#228]
Hey, 

It looks like you might not be maintaining the library anymore based on some of the comments here: https://github.com/SirCmpwn/RedditSharp/commit/c9ad0efaecde8a8a6c10936b4f4eeb72975935cc

Instead of doing a fork, would you be interested in maybe moving the project to it's own organization/repo? It would be nice to have all the history in place plus all the pre-existing links to the project out on the web will still work. 

You can add other people to the organization, if they are interested in taking over the project. I know @CrustyJew expressed his interest elsewhere. Thoughts?

**Comment by SirTony** [comment]
>You can add other people to the organization, if they are interested in taking over the project.

It's possible to give people write permissions to personal repos so they can push directly without having to send a PR.

The problem with doing that is vetting the people to ensure they won't run things into the ground. Part of the purpose of PRs is to be able to review and approve or reject changes before committing them to main repo.

(Note: I don't speak for @SirCmpwn or the RedditSharp project as a whole)

**Comment by CrustyJew** [comment]
I'm willing to maintain or help maintain this project, but I think the best way to do it would be to have @SirCmpwn transfer ownership of the repo. They recommended just hard forking it, but that doesn't seem ideal to me but I'm willing to do that if necessary. 

Any github fork will reference this project as the parent, and reuploading it to a new repository seems weird and would likely require a rename. 

Again, that's fine with me if that's the route we need to go, but it doesn't seem ideal.

**Comment by Kkloss** [comment]
@SirTony I made the suggestion to move for a couple of reasons: 

1) The current repo has a lot of SEO juice and is referenced in a ton of blog posts, SO threads, etc. It's going to be nearly impossible for a fork to rank higher, even if it has a ton of activity. There is also a lot of history in the issues and PR's that would be lost with a hard fork.

2) Also if you keep the repo where it is currently, you would still be relying on @SirCmpwn to maintain the permissions if someone new wants access to the repo (at least I believe that's how GitHub works). It's not clear how much time/effort he will be allocate going forward but with a separate repo, it won't be an issue since other core members will be able to maintain those things. @SirCmpwn can still participate as he is able to.

**Comment by SirTony** [comment]
Fair points, I hadn't considered that.

**Comment by CrustyJew** [comment]
@SirCmpwn I still think it would be best for others if you could transfer ownership of this repository instead of forcing a fork. That way we don't lose people along the way. Are you willing to do that?

**Comment by CrustyJew** [comment]
@SirCmpwn Thanks for adding me as a contributor so I can continue to maintain it. Can you change the title of the Repo to reflect that it is maintained still, or can you transfer ownership of the repository to me so that I can fully maintain it and you won't need to do anything further in the future.

https://help.github.com/articles/about-repository-transfers/

Thanks!

**Comment by Sharparam** [comment]
I think it would be better to transfer it to an organization. It would make future maintainer replacements easier and an owner change wouldn't mean a change in the project URL. Multiple core contributors would also be more easily maintained.

**Comment by CrustyJew** [comment]
I don't disagree and that's basically what I was planning on doing if the repository is transferred over to me. I believe after a transfer, the redirect occurs automatically, and hopefully the same applies when adding it to an organization.

**Comment by CrustyJew** [comment]
@SirCmpwn Can I get any follow up to this or any updates on your thoughts?

**Comment by SirCmpwn** [comment]
I've given you access to this repository to author commits directly, merge PRs, and so on. That should be enough. If you don't like it do a hard fork like I initially suggested.

**Comment by CrustyJew** [comment]
@SirCmpwn I appreciate the commit access, but it doesn't solve the issue of changing the description on the repository to reflect that it is still maintained.

Also, GitHub doesn't really support hard forks very well and we will lose all SEO and such. Is there any particular concern you have with changing ownership of the repository since you are no longer interested in maintaining it?

**Comment by CrustyJew** [comment]
@SirCmpwn Thanks for changing the repository description to indicate it is still maintained, but is there any reason in particular you aren't wanting to transfer ownership of the repository? It'll prevent issues going forward that I'd need to bug you about (like adding more collaborators if we need them) and it will maintain links and search results so that people can still find the repository easily.

**Comment by SirCmpwn** [comment]
I want RedditSharp to die and franky I want Reddit to die as well. I'm disgusted with what it's become and I want no part in it. I'm willing to make some concessions like making you a collaborator to make sure bugs get fixed and I don't fuck over anyone who depends on this library, but if you want more than that you're going to have to make a hard fork.

**Comment by CrustyJew** [comment]
@SirCmpwn you are by very definition fucking anyone over who uses this library by first marking it as unmaintained and being completely opposed to transferring the repository for no reason besides spite.

I'm sorry you don't like Reddit for whatever reason, but this is honestly the most childish thing I think I've seen on here.

**Comment by SirCmpwn** [comment]
Alright, that's enough.
