### ISSUE TITLE
Migrate the library to Win8 or WP8

### ISSUE THREAD

**Issue by yamspog** [SirCmpwn/RedditSharp#5]
The library works great for win7 but does not work with windows 8 nor with windows phone 7/8.  With the massive push by Microsoft to publicise the new OS and new phone, it would be nice to have the software migrated to support these platforms.

**Comment by SergueiFedorov** [comment]
Was this issue resolved? It's pretty old.

**Comment by SirCmpwn** [comment]
No, it wasn't, and I'm going to close it for the same reasons as the other one.

**Comment by SergueiFedorov** [comment]
I thought they were related. Thank you.
